disaster/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.first),
    path('login/', views.login),
    path('index/', views.index),
    path('index1/', views.index),
    path('login/', include('login.urls',namespace='login')),
    path('register/', views.register),
    path('logout/', views.logout),
    path('table/', views.table),
    path('remark/', views.remark),
    path('spread/', views.spread),
    path('people/', views.people),
    path('captcha/', include('captcha.urls')),  # 增加这一行
    path('search_form/',views.search_form),
    path('search_result/', views.search_result),
    path('show/<int:id>/',views.show,name="show"),
]

login/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.urls import include
from login import views
app_name='login'
urlpatterns = [
    # path('table/', views.table),
    # path('spread/', views.spread),
    # path('remark/', views.remark),
    # path('people/', views.people),
    path('search_result/', views.search_result,name='search_result'),
    path('search_form/', views.search_form,name='search_form'),
    path('login/', views.login,name='login'),
    path('index/', views.index,name='index'),
    path('index1/', views.index,name='index1'),
    url(r'^table/(?P<id>[0-9]+)$', views.table, name='table'),
    url(r'^spread/(?P<id>[0-9]+)$', views.spread, name='spread'),
    url(r'^remark/(?P<id>[0-9]+)$', views.remark, name='remark'),
    url(r'^people/(?P<id>[0-9]+)$', views.people, name='people'),
]

login/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Username",'autofocus': ''}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': "Password"}))
class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)

login/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from . import models
from . import forms
from .models import events
import hashlib
from django.shortcuts import render_to_response
from django.core.paginator import Paginator
import json
# Create your views here.


def index(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')
    events=models.events.objects.all()
    return render(request, 'login/search_form.html',{'events': events})



def login(request):
    if request.method == 'POST':
        login_form = forms.UserForm(request.POST)
        message = '请检查填写的内容！'
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')

            try:
                user = models.User.objects.get(name=username)
            except :
                message = '用户不存在！'
                return render(request, 'login/login.html', locals())

            if user.password == hash_code(password):
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                return redirect('/search_form/')
            else:
                message = '密码不正确！'
                return render(request, 'login/login.html', locals())
        else:
            return render(request, 'login/login.html', locals())

    login_form = forms.UserForm()
    return render(request, 'login/login.html', locals())


def register(request):
    # if request.session.get('is_login', None):
    #     return redirect('/search_form/')

    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')
            sex = register_form.cleaned_data.get('sex')

            if password1 != password2:
                message = '两次输入的密码不同！'
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:
                    message = '用户名已经存在'
                    return render(request, 'login/register.html', locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:
                    message = '该邮箱已经被注册了！'
                    return render(request, 'login/register.html', locals())

                new_user = models.User()
                new_user.name = username
                new_user.password = hash_code(password1)
                new_user.email = email
                new_user.sex = sex
                new_user.save()

                return redirect('/login/')
        else:
            return render(request, 'login/register.html', locals())
    register_form = forms.RegisterForm()
    return render(request, 'login/register.html', locals())



def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/login/")
    request.session.flush()
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/login/")
def hash_code(s, salt='disaster'):# 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()
def table(request,id):
    event = models.events.objects.get(id=id)
    hots = models.past_hours_hot.objects.get(id=id)
    return render(request, 'login/table.html',{'event':event,'hots':hots})


def remark(request,id):
    event = models.events.objects.get(id=id)
    person=models.person_remarks.objects.get(id=id)

    word_cloud=event.word_cloud
    datalist = word_cloud.split('*')
    datalist = [json.loads(j) for j in datalist]
    return render(request, 'login/remark.html', {'word_cloud':datalist,'event': event,'person':person})


def spread(request,id):
    event = models.events.objects.get(id=id)
    return render(request, 'login/spread.html', {'event': event})


def people(request,id):
    user = models.User.objects.name
    event = models.events.objects.get(id=id)
    number = event.famale + event.male
    female = event.famale / number*100
    male = event.male / number*100
    return render(request, 'login/people.html', {'event': event,'female':female,'male':male,'user':user})

def search_form(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')
    if request.GET.get('order')=='hot':#字段热度，不是事件热度
        articles_list=events.objects.all().order_by('-hot')[:30]
        order='hot'
    else:
        articles_list=events.objects.all()[:30]
        order='normal'
    paginator=Paginator(articles_list,6)
    page=request.GET.get('page')
    articles=paginator.get_page(page)
    context={'articles':articles,'order':order}
    return  render_to_response('login/search_form.html',context)

def search_result(request):
    if 'q' in request.GET or request.GET['q']:
        q=request.GET['q']
        search=events.objects.filter(event_name__icontains=q)
        return render_to_response('login/search_result.html',{'search':search,'query':q})
    else:
        render_to_response('login/search_form.html',{'error':True})
def show(request,id):
    content=events.objects.get(id=id)
    return render_to_response('login/show.html',{"content":content})
def first(request):
    pass
    return render(request, 'login/first.html', locals())

templates/login/first.html
{% load static %}
<!DOCTYPE html>

<html lang="en-us">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>微博舆情传播首页</title>

<!-- Load fonts -->


<link href='{% static 'login/madecss/fonts1.css' %}' rel='stylesheet' type='text/css'>
<link href='{% static 'login/madecss/fonts2.css' %}' rel='stylesheet' type='text/css'>

<!-- Load css styles -->

	<link rel="stylesheet" href="{% static 'login/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'login/css/font-awesome.css' %}">
	<link rel="stylesheet" href="{% static 'login/css/style.css' %}">

</head>
<body>
<div class="jumbotron home home-fullscreen" id="home">
	<div class="mask"></div>
	<a href="#" class="logo">
		<img src="{% static 'login/img/logo.png' %}" alt="Moderno - Theme">
	</a>
	<a href="" class="menu-toggle" id="nav-expander"><i class="fa fa-bars"></i></a>
	<!-- Offsite navigation -->
	<nav class="menu">
		<a href="#" class="close"><i class="fa fa-close"></i></a>
		<h3>Menu</h3>
		<ul class="nav">
			<li><a data-scroll href="#home">Home</a></li>
			<li><a data-scroll href="#services">Service</a></li>
			<li><a data-scroll href="#portfolio">Portfolio</a></li>
			<li><a data-scroll href="#contact">Contact</a></li>
		</ul>
		<ul class="social-icons">
			<li><a href=""><i class="fa fa-facebook"></i></a></li>
			<li><a href=""><i class="fa fa-twitter"></i></a></li>
			<li><a href=""><i class="fa fa-dribbble"></i></a></li>
			<li><a href=""><i class="fa fa-behance"></i></a></li>
			<li><a href=""><i class="fa fa-pinterest"></i></a></li>
		</ul>
	</nav>
	<div class="container">
		<div class="header-info">
			<h1 class="title">微博传播分析</h1>
			<p class="subtitle">单条微博传播路径精准刻画
			</p>
            <div class="container1">
			<a href="{% url 'login:login'%}" class="btn1 ">进入首页</a>
            </div>
            </div>
	</div>
</div>
<!-- Services section start -->
<section id="services">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<div class="service-item">
					<div class="icon"><i class="fa fa-diamond"></i></div>
					<h3>We Are Creative</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam,
						quis nostrud exercitation ullamco.
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="service-item">
					<div class="icon"><i class="fa fa-gear"></i></div>
					<h3>We Have Skills</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua.
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="service-item">
					<div class="icon"><i class="fa fa-life-ring"></i></div>
					<h3>We Love To Help</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Services section end -->

<!-- Load jQuery -->
<script type="text/javascript" src="{% static 'login/js/jquery-1.11.2.min.js' %}"></script>

<!-- Load Booststrap -->
<script type="text/javascript" src="{% static 'login/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'login/js/smooth-scroll.js' %}"></script>

<!-- Load custom js for theme -->
<script type="text/javascript" src="{% static 'login/js/app.js' %}"></script>
</body>
</html>

templates/login/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "login/base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <!-- 面包屑导航 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
               <a href="?order=normal">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="?order=hot">
                    最热
                </a>
            </li>
            <span class="input-group-btn" style="margin-left: 700px">
               <button class="btn btn-info btn-search"><a href="http://s175041133.gitee.io/covid-19_info/">疫情数据展示</a></button>
            </span>
        </ol>
    </nav>

    <!-- 搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" action="{% url 'login:search_result'%}" method="get">
                <label class="sr-only">content</label>
{#                <input type="text"#}
{#                    class="form-control mb-2 mr-sm-2"#}
{#                    name="q"#}
{#                    placeholder="搜索事件..."#}
{#                >#}
{#                <input type="submit" value="搜索"/>#}

            <input type="text" class="form-control"  name="q" placeholder="请输入搜索关键字"  >
            <span class="input-group-btn">
               <button type="submit" class="btn btn-info btn-search">查找</button>
            </span>

            </form>
        </div>
    </div>

    <!-- 列表循环 -->

        <div class="row mt-2">
    {% for article in articles %}
        <div class="col-4 mb-4">
        <div class="card h-100">
    <h4 class="card-header"><a href="{% url 'login:table' article.id %}" target="_blank">{{ article.event_name }}</a></h4>
            <div class="card-body">
        <p class="card-text">{{ article.event_description }}</p></div>
            <div class="card-footer">
        <p class="card-text" align="center">{{ article.hot }}
        <img src="/static/login/img/huohua.png" height="25" width="25"></p>
        <p class="card-text" align="center">{{ article.time|date:"Y年n月d日" }}</p>
            </div>
        </div>
        </div>

    {% endfor %}
</div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}"
                       class="btn btn-success"
                    >
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

</div>

{% endblock content %}
</body>
</html>

templates/login/search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询结果</title>
</head>
<body>
{% extends "login/base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<h4>你要搜索的关键词是:“<span style="color: #b21f2d"><strong>{{ query }}</strong></span>”</h4>
{% if search  %}
<h4>共找到<span style="color: #b21f2d">{{ search|length }}条记录</span></h4><p><a href="{% url 'login:search_form'%}">返回首页</a></p>
    <div class="container">
    <div class="row mt-2">
    {% for i in search %}
        <div class="col-4 mb-4">
        <div class="card h-100">
    <h4 class="card-header"><a href="{% url 'login:table' i.id %}" target="_blank">{{ i.event_name }}</a></h4>
            <div class="card-body">
        <p class="card-text">{{ i.event_description }}</p></div>
            <div class="card-footer">
        <p class="card-text" align="center">{{ i.hot }}
        <img src="/static/login/img/huohua.png" height="25" width="25"></p>
        <p class="card-text" align="center">{{ i.time }}</p>
            </div>
        </div>
        </div>

    {% endfor %}

{% else%}
<p>抱歉，没有找到包含您所查找关键词的内容</p>
    <p><a href="{% url 'login:search_form'%}">返回首页</a></p>
{% endif %}
    </div>
    </div>

{% endblock content %}
</body>
</html>

templates/login/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{content.event_name }}</h1>
<h1>{{content.event_description }}</h1>
<h1>{{content.time}}</h1>
<h1>{{ content.pass_onehour_hot }}</h1>
<h1>{{ content.male }}</h1>
<h1>{{ content.female }}</h1>
</body>
</html>

templates/login/table.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
	
	<link href="{% static 'login/madecss/fonts3.css' %}" rel="stylesheet">
<!-- <link rel="stylesheet" href="assets/materialize/css/materialize.min.css" media="screen,projection" />-->
    <link href="{% static 'login/assets/materialize/css/materialize.min.css' %}" media="screen,projection" rel="stylesheet"/>
    <!-- Bootstrap Styles-->
   <!--  <link href="assets/css/bootstrap.css" rel="stylesheet" />-->
    <link href="{% static 'login/assets/css/bootstrap.css' %}" rel="stylesheet"/>
    <!-- FontAwesome Styles-->
<!--    <link href="assets/css/font-awesome.css" rel="stylesheet" /> -->
    <link href="{% static 'login/assets/css/font-awesome.css' %}" rel="stylesheet"/>
    <!-- Morris Chart Styles-->
<!--    <link href="assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />  -->
    <link href="{% static 'login/assets/js/morris/morris-0.4.3.min.css' %}" rel="stylesheet"/>
    <!-- Custom Styles-->
    <!--    <link href="assets/css/custom-styles.css" rel="stylesheet" /> -->
    <link href="{% static 'login/assets/css/custom-styles.css' %}" rel="stylesheet"/>
    <!-- Google Fonts-->
    <link href='{% static 'login/madecss/fonts4.css' %}' rel='stylesheet' type='text/css' />
   <!-- <link rel="stylesheet" href="assets/js/Lightweight-Chart/cssCharts.css"> -->
     <link href="{% static 'login/assets/js/Lightweight-Chart/cssCharts.css' %}" rel="stylesheet"/>
     <!-- echarts-->
  <!--  <script src="echarts/echarts.min.js"></script> -->
    <script src="{% static 'login/echarts/echarts.min.js' %}"></script>
  <!--  <script src="echarts/echarts.js"></script> -->
    <script src="{% static 'login/echarts/echarts.js' %}"></script>
    <script src="{% static 'login/madecss/bootstrap.css' %}"></script>
    <script type="text/javascript" src="{% static 'login/madecss/echarts.js' %}"></script>
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle waves-effect waves-dark" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a class="navbar-brand waves-effect waves-dark" href="index.html"><span class="glyphicon glyphicon-search"></span><strong>掘微舆情</strong></a>
				
		<div id="sideNav" href=""><i class="material-icons dp48">toc</i></div>
            </div>

            <ul class="nav navbar-top-links navbar-right"> 
				  <li><a class="dropdown-button waves-effect waves-dark" href="#!" data-activates="dropdown1"><i class="fa fa-user fa-fw"></i> <b>yuanyilin</b> <i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
        </nav>
		<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
{#<li><a href="#"><i class="fa fa-user fa-fw"></i> My Profile</a>#}
{#</li>#}
{#<li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>#}
{#</li> #}
<li><a href="/logout/"><i class="fa fa-sign-out fa-fw"></i> 登出</a>
</li>
</ul>
 
	   <!--/. NAV TOP  左边侧栏--> 
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                   <!--  <li>
                        <a class=" waves-effect waves-dark" href="index.html"><i class="fa fa-home"></i> 首页</a>
                    </li> -->
                    <li>
                        <a class="waves-effect waves-dark" href="{% url 'login:search_form' %}"><i class="fa fa-home"></i> 首页</a>
                    </li>
                    <li>
                        <a href="{% url 'login:table' event.id %}" class="active-menu waves-effect waves-dark"><i class="fa fa-list-alt"></i> 事件概况</a>
                    </li>
                    <li>
                        <a href="{% url 'login:spread' event.id %}" class="  waves-effect waves-dark"><i class="fa fa-signal"></i> 传播分析</a>
                    </li>
                    <li>
                        <a href="{% url 'login:remark' event.id %}" class=" waves-effect waves-dark"><i class="fa fa-comments"></i> 舆论聚合</a>
                    </li>
                    <li>
                        <a href="{% url 'login:people' event.id %}" class="waves-effect waves-dark"><i class="fa fa-user"></i>人群画像</a>
                    </li>
                    
                    
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
      <!-- 	主内容 -->
		<div id="page-wrapper">
		  <div class="header"> 
                        <h1 class="page-header">
                            事件概况
                        </h1>
						<ol class="breadcrumb">
					  <li><a href="table.html">Detail</a></li>
					  <li class="active">Data</li>
					</ol> 
									
		</div>
            <div id="page-inner">

			 <div class="col-md-12">
	               <div class="card">
	               	 <div class="icon-preview col s6 m3"><i class="fa fa-question-circle"></i> 事件名</div>
						<div class="card-content">
							 <div class="alert alert-info">

									<strong style="font-size: 20px;">{{ event.event_name }}</strong>

                             </div>
								<div class="icon-preview col s6 m3" style="margin-left: 10px;"><i class="fa fa-bars"></i> 事件概况</div>
	  							 <div class="alert alert-success" >
									{{ event.time|date:"Y年n月d日" }},{{ event.event_description }}
								</div>
	</div>
  </div>
			</div>	


				
                <div class="col-md-12">

                    <div class="card">
                    	<div class="icon-preview col s6 m3"><i class="material-icons dp48">equalizer</i><span>事件趋势</span></div>
                    <div id="hot" style="width: 600px;height:500px;"></div>
                    </div>
                 <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var Hot= echarts.init(document.getElementById('hot'));

        // 指定图表的配置项和数据
        option = {
    tooltip: {
        trigger: 'axis'
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            saveAsImage : {show: true}
        }
    },
    xAxis: [{
        type: 'category',
        {% now "H" as nowtime%}
        data: ['{{ nowtime|add:"-6"}}:00','{{ nowtime|add:"-5"}}:00','{{ nowtime|add:"-4"}}:00','{{ nowtime|add:"-3"}}:00','{{ nowtime|add:"-2"}}:00','{{ nowtime|add:"-1" }}:00'],
        axisLine: {
            lineStyle: {
                color: "#999"
            }
        }
    }],
    yAxis: [{
        type: 'value',
        splitNumber: 4,
        splitLine: {
            lineStyle: {
                type: 'dashed',
                color: '#DDD'
            }
        },
        axisLine: {
            show: false,
            lineStyle: {
                color: "#333"
            },
        },
        nameTextStyle: {
            color: "#999"
        },
        splitArea: {
            show: false
        }
    }],
    series: [{
        name: '热度',
        type: 'line',
        data: [{{ hots.past_sixhour_hot }},{{ hots.past_fivehour_hot }},{{ hots.past_fourhour_hot }},{{ hots.past_threehour_hot }},{{ hots.past_twohour_hot }},{{ hots.past_onehour_hot }}],
        lineStyle: {
            normal: {
                width: 8,
                color: {
                    type: 'linear',

                    colorStops: [{
                        offset: 0,
                        color: '#A9F387' // 0% 处的颜色
                    }, {
                        offset: 1,
                        color: '#48D8BF' // 100% 处的颜色
                    }],
                    globalCoord: false // 缺省为 false
                },
                shadowColor: 'rgba(72,216,191, 0.3)',
                shadowBlur: 10,
                shadowOffsetY: 20
            }
        },
        itemStyle: {
            normal: {
                color: '#fff',
                borderWidth: 10,
                /*shadowColor: 'rgba(72,216,191, 0.3)',
                shadowBlur: 100,*/
                borderColor: "#A9F387"
            }
        },
        smooth: true
    }]
};
        // 使用刚指定的配置项和数据显示图表。
        Hot.setOption(option);
    </script>
            




























            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
<!--   <script src="assets/js/jquery-1.10.2.js"></script> -->
	<script src="{% static 'login/assets/js/jquery-1.10.2.js' %}"></script>
	<!-- Bootstrap Js -->
<!--    <script src="assets/js/bootstrap.min.js"></script> -->
	<script src="{% static 'login/assets/js/bootstrap.min.js' %}"></script>
<!--	<script src="assets/materialize/js/materialize.min.js"></script> -->
	<script src="{% static 'login/assets/materialize/js/materialize.min.js' %}"></script>
    <!-- Metis Menu Js -->
 <!--   <script src="assets/js/jquery.metisMenu.js"></script> -->
         <script src="{% static 'login/assets/js/jquery.metisMenu.js' %}"></script>
    <!-- Morris Chart Js -->
  <!--  <script src="assets/js/morris/raphael-2.1.0.min.js"></script> -->
        <script src="{% static 'login/assets/js/morris/raphael-2.1.0.min.js' %}"></script>
<!--    <script src="assets/js/morris/morris.js"></script> -->
	<script src="{% static 'login/assets/js/morris/morris.js' %}"></script>
	
<!--	<script src="assets/js/easypiechart.js"></script> -->
        <script src="{% static 'login/assets/js/easypiechart.js' %}"></script>
<!--	<script src="assets/js/easypiechart-data.js"></script> -->
	 <script src="{% static 'login/assets/js/easypiechart-data.js' %}"></script>
<!--	 <script src="assets/js/Lightweight-Chart/jquery.chart.js"></script> -->
	 <script src="{% static 'login/assets/js/Lightweight-Chart/jquery.chart.js' %}"></script>
    <!-- Custom Js -->
  <!--  <script src="assets/js/custom-scripts.js"></script> -->
        <script src="{% static 'login/assets/js/custom-scripts.js' %}"></script>


</body>

</html>